services:
  db:
    image: postgres:17
    container_name: servidor-bd1
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - bd1_data:/var/lib/postgresql/data

volumes:
  bd1_data: